### ISSUE TITLE
vscode的运行情况

### ISSUE THREAD

**Issue by 12101111** [weolar/miniblink49#140]
1.23,1.24:可以运行,需要修改native-keymap,spdlog

问题:

 1. 每次运行总是打开init.js
 2. 文件夹的文件列表无法显示
 3. 终端无法运行任何shell

```
{ errorCode: 'load',
 moduleId: 'node-pty',
neededBy: [ 'vs/workbench/parts/terminal/node/terminalProcess' ],
 detail: 
 Error: %1 is not a valid Win32 application. 
 \\?\C:\Users\...\AppData\Local\Temp\FA55.tmp.node
 at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:184:28)
 at Object.Module._extensions..node (module.js:597:18)
 at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:198:24)
 at Module.load (module.js:487:32)
 at tryModuleLoad (module.js:446:12)
 at Function.Module._load (module.js:438:3)
 at Module.require (module.js:497:17)
 at require (internal/module.js:20:19)
 at Object.<anonymous> (C:\...\resources\app\node_modules.asar\node-pty\lib\windowsPtyAgent.js:9:11)
 at Module._compile (module.js:570:32) }
```
1.25无法运行
```
setAsDefaultProtocolClientApi
nullFunction
```
1.26无法运行
```
TypeError: Cannot read property '_setApplicationMenu' of null
    at Function.Menu.setApplicationMenu (C:\...\resources\miniblink.asar\browser\api\menu.js:139:6)
    at e.install (C:\...\resources\app\out\vs\code\electron-main\main.js:363:197)
    at new e (C:\...\resources\app\out\vs\code\electron-main\main.js:359:218)
    at t.create (C:\...\resources\app\out\vs\code\electron-main\main.js:52:694)
    at e._createInstance (C:\...\resources\app\out\vs\code\electron-main\main.js:209:325)
    at e.createInstance (C:\...\resources\app\out\vs\code\electron-main\main.js:208:600)
    at new e (C:\...\resources\app\out\vs\code\electron-main\main.js:380:442)
    at t.create (C:\...\resources\app\out\vs\code\electron-main\main.js:52:694)
    at e._createInstance (C:\...\resources\app\out\vs\code\electron-main\main.js:209:325)
    at e._createAndCacheServiceInstance (C:\...\resources\app\out\vs\code\electron-main\main.js:210:291)
    at e._getOrCreateServiceInstance (C:\...\resources\app\out\vs\code\electron-main\main.js:209:462)
    at Object.get (C:\...\resources\app\out\vs\code\electron-main\main.js:208:153)
    at t.openFirstWindow (C:\...\resources\app\out\vs\code\electron-main\main.js:488:769)
    at C:\...\resources\app\out\vs\code\electron-main\main.js:486:363
    at e.invokeFunction (C:\...\resources\app\out\vs\code\electron-main\main.js:208:279)
    at C:\...\resources\app\out\vs\code\electron-main\main.js:486:327
    at n.Class.define.cancel.then (C:\...\resources\app\out\vs\code\electron-main\main.js:91:201)
    at C:\...\resources\app\out\vs\code\electron-main\main.js:486:246
    at n.Class.define.cancel.then (C:\...\resources\app\out\vs\code\electron-main\main.js:91:201)
    at t.startup (C:\...\resources\app\out\vs\code\electron-main\main.js:485:604)
    at C:\...\resources\app\out\vs\code\electron-main\main.js:497:539
    at Object.v [as _notify] (C:\...\resources\app\out\vs\code\electron-main\main.js:84:572)
    at Object.enter (C:\...\resources\app\out\vs\code\electron-main\main.js:87:924)
    at n.Class.derive._oncancel._run (C:\...\resources\app\out\vs\code\electron-main\main.js:89:790)
    at n.Class.derive._oncancel._completed (C:\...\resources\app\out\vs\code\electron-main\main.js:89:231)
    at Server.<anonymous> (C:\...\resources\app\out\vs\code\electron-main\main.js:170:657)
    at Server.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1285:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by weolar** [comment]
好的，我修复下。vscode的最新版本我还没跑过
