### ISSUE TITLE
启动之后无界面弹出，后台进程残留，显示未找到模块Crypto

### ISSUE THREAD

**Issue by miswanting** [weolar/miniblink49#195]
[dbgview.log](https://github.com/weolar/miniblink49/files/2565108/dbgview.log)

**Comment by dv0** [comment]
我也遇到相同问题，用的组件如下
  "dependencies": {
    "electron-compile": "^6.4.3",
    "electron-squirrel-startup": "^1.0.0",
    "ftp": "^0.3.10",
    "request": "^2.88.0"
  },

**Comment by dv0** [comment]
我重新再试了下，像是electron-forge make编译出来的app.asar都会出现无界面弹出并进程残留，但是直接运行js源码是可以弹出界面的。

**Comment by weolar** [comment]
大概知道原因了，是因为我把opengl去掉导致
@dv0

**Comment by gdh1995** [comment]
请问还会加入opengl模块的支持吗？最新的1.29版vs code替换miniblink-electron后，DbgView里也是显示这个错误。

至于作者您给的旧的1.23版vs code，在我的win10上有错误，显示不了文件夹对话框，走命令行也打不开工程文件夹

**Comment by weolar** [comment]
说错了，是我最近把openssl换成了wolfssl导致的，这个问题我这几天来处理一下吧

**Comment by weolar** [comment]
@gdh1995

**Comment by gdh1995** [comment]
嗯谢谢。

**Comment by weolar** [comment]
@gdh1995 有asar吗，发给我试试

**Comment by gdh1995** [comment]
是miniblink-181127.rar里的mini-electron.asar，和VS Code 1.29.1 (32位）
https://pan.baidu.com/s/109NWCWwlhk0SuABqmqupFA https://vscode.cdn.azure.cn/stable/bc24f98b5f70467bc689abf41cc5550ca637088e/VSCode-win32-ia32-1.29.1.zip

**Comment by gdh1995** [comment]
最新发布的miniblink-181214.rar，配合VSCode-win32-ia32-1.30.0.zip的结果是：

启动问题：
* resources\app\out\vs\code\electron-main\main.js里`this._win.isSimpleFullScreen`是undefined
  * 把这个函数删了后，能启动了，但点最大化按钮时直接全屏。

启动后表现：
* 打开工程文件夹失败，似乎没有什么有效的debug log

DebugView找到的异常：
* miniblink.asar/browser/api/net.js里，hasCrypto是0，造成https请求（比如检查更新）抛“不支持的协议”异常
* sqlite3某个地方报告“callback expected”异常，这个异常经常出现
* 还有一些标注了internal/process/warning.js的unhandled promise rejection: TypeError之类的异常

关于hasCrypto：
``` json
{"http_parser":"2.7.0","node":"6.9.2","uv":"1.9.1","zlib":"1.2.11","ares":"1.10.1-DEV","modules":"48","openssl":"0","atom-project-name":"3.0.1","atom-shell":"3.0.1","chrome":"52.0.2743.82","electron":"3.0.1"}
```

关于sqlite3:
```
[6676] [main 12:20:01 GMT+0800 (中国标准时间)] TypeError: Callback expected
[6676]     at Database.run (R:\working\VSCode-win32-ia32-1.30.0\resources\app\node_modules.asar\vscode-sqlite3\lib\sqlite3.js:18:25)
[6676]     at Database.<anonymous> (R:\working\VSCode-win32-ia32-1.30.0\resources\app\out\vs\code\electron-main\main.js:185:803)
[6676]     at R:\working\VSCode-win32-ia32-1.30.0\resources\app\out\vs\code\electron-main\main.js:185:780
```
